### ISSUE TITLE
Mobile responsive styling

### ISSUE THREAD

**Issue by cagrimmett** [scripting/a8c-FeedLand-Support#39] opened 2023-11-04 20:14 UTC
FeedLand uses an old version of Bootstrap. Perhaps mobile styling might be as simple as applying the right Bootstrap classes to the UI?

**Comment by cagrimmett** [comment] 2023-11-06 17:36
Notes from our call on 2023-11-06:
- If markup changes are needed, bring them up to Dave and chat with him.
- For CSS Changes perhaps call a function to load in CSS from a file first to override everything, kind of like we do for news product templates

**Comment by scripting** [comment] 2023-11-06 20:04
@fmfernandes @cagrimmett -- new feature

1. Create a stylesheet, put it somewhere where it's publicly accessible.
2. Assign the URL of the spreadsheet to `localStorage.urlStartupStylesheet`.
3. Reload FeedLand.

The stylesheet is loaded after all other files are read. 

### Example

`localStorage.urlStartupStylesheet = "http://scripting.com/publicfolder/feedland/misc/testStartupStylesheet.css"`

**Comment by scripting** [comment] 2023-11-23 14:53
@fmfernandes -- i want this in a step-by-step fashion, the way I write instructions to update the server.

1. do this
2. now this
3. do this
4. etc.

No interruptions with why we're doing any bit, and if there's any doubt about what it means, I won't do it, because I don't want a drawn out process, or to break things. I want confidence that what I'm being asked to do has been thought through, and I can do the work and be pretty sure it'll work if i do it carefully. ;-)

**Comment by scripting** [comment] 2023-11-23 14:54
And even if we're both super careful it still will break! (As we found out recently.)

**Comment by scripting** [comment] 2023-11-23 17:14
Okay -- this isn't a nit imho -- you say that's what you did, are you saying I should do it? Or do you want me to review it and ask questions? I'm going to assume the latter.

You're saying I should include a newer version of Bootstrap. This is something I wouldn't do without a lot of time for testing. How could it *not* break stuff? There is a mountain of code that depends on Bootstrap. I just spent a couple of hours dealing with stuff exactly like this, getting rivers to render in my prototype of the new Scripting News. And it's something I did off on the side, without any impact on existing users. So if I break something, for now at least, I'm the only one who sees it.

I couldn't do this with confidence. Would you make such a recommendation to the maintainers of WordPress without some explanation of why it should be trusted??

So I assume you were trying to get me to ask this question?? ;-)

**Comment by scripting** [comment] 2023-11-23 17:51
@fmfernandes -- thank you. Now I understand. :-)

I'll set up a testbed for this anyway, and see what happens. If it looks reasonable, I'll release it. How does that sound?

**Comment by scripting** [comment] 2023-11-24 14:27
@fmfernandes -- I made the changes above. 

I didn't add the styles to index.html, that's not how I do it. There's a styles.css file, which is where those things go.

However looking at the actual settings, at some point I will put them in their respective .css files. I try to keep the modules separate, makes it possible to use different components in other apps without polluting the CSS stylespace with extra stuff. CSS is so hard to manage that way.

**Comment by scripting** [comment] 2023-11-25 14:39
I use FeedLand on an iPad Mini, and the menus fit, by design, so there's no need for the mobile compromise there. Is there a way to disable the new optimizations on tablets?

**Comment by scripting** [comment] 2023-11-28 20:00
@fmfernandes @cagrimmett -- for example, we could get rid of all but the first and last menus, and in a pinch we could probably do away with the last menu too. 

i think that's a far better way of managing things -- think about what the scope of a mobile app is for. it's not for studying as much as it is skimming. i'm sure some people would disagree of course.

**Comment by cagrimmett** [comment] 2023-11-29 19:09
Based on @scripting's voicemail in Slack, Dave wants to drop bootstrap mobile. He is confident the menu will work on mobile without being collapsed.

On the River, Dave is open to design ideas. I have three:
1. Hide `.divRiverItemFooter` completely unless the river item is expanded.
2. Reduce the max-height of `.divRiverItemBody` to 100px on mobile.
3. Bring the favicon inline with the content. Having it outside on desktop looks great, but takes up too much valuable space on mobile.

In terms of the first steps for the River, @fmfernandes hit the nail on the head above. The main issue right now is that `.divRiverDisplay` and `.divRiverContent` have fixed widths and those need to be set to `auto`

**Comment by cagrimmett** [comment] 2023-11-29 19:22
One more thing we need to consider: How do we handle tabs on mobile? Any more than 3 on the News page won't fit.

**Comment by scripting** [comment] 2023-11-29 19:29
I made these changes and also tightened up the margins. 

<img width="348" alt="image" src="https://github.com/scripting/a8c-FeedLand-Support/assets/1686843/e45d5d07-5a38-4d60-aec9-bf7bfdf6bb34">

**Comment by scripting** [comment] 2023-11-29 19:30
Where we really need the menu for mobile is for the tabs.

**Comment by scripting** [comment] 2023-12-07 15:35
Closing this because we're working on it in another thread.

**Closed by scripting** 2023-12-07 15:35 UTC
